IP2B2/Front-End

- src/app/auth/extra-data-required/page.js
- src/app/auth/extra-data-required/registerPage.module.css
**_Extra Data Required Page_**
Implementare simplă a paginii de Register (Partea a 2-a), în care utilizatorului îi sunt cerute date suplimentare.
A fost nevoie de un formular care să permită inserarea unor date precum numele, prenumele, rolul, parola (+verificarea acesteia).
Spațierile au fost respectate întru totul, corespunzând design-ului de pe Figma. https://www.figma.com/design/LEQjT08rDaFw0YNEO5mIBE/IP-2025?node-id=123-211&t=DkBjQPFtOTFzm619-0
Probabil nu mai sunt necesare alte rafinări.
> #005 extra data required

- src/app/auth/register/page.js
- src/app/auth/register/register.module.css
S-a creat pagina /auth/register cu un formular simplu pentru email si numar matricol.
> #004_Creare-pagina-Register-First-Part

- src/lib/logic/AuthValidators.js
Code cleaning
Changed AuthValidators.js
Changed: Login form doesn't display error if fields are empty.
> validators refactor

- src/app/auth/extra-data-required/page.js
- src/app/auth/login/page.js
- src/app/auth/register/page.js
Am creat:
Login → Register (daca nu are cont)
Login → Landing Page
Register (first part) → Register (second part)
Register (second part) → Landing Page
Task-ul #009 cu crearea landing page-ului nu a fost pus pe main, deci nu am putut face redirectionarea Landing page(logout) → Login
> #010-Redirectionare-pagini

- src/app/auth/confirm-mail/confirmMail.module.css
- src/app/auth/confirm-mail/page.js
- src/app/page.js
Aici este implementarea designului paginii de Confirmare Mail.
Am impartit efectuarea acestei implementari in 5 parti:
- titlu
- subtitlu
- zonă text
- buton timer
- buton "Inapoi la autentificare".
La începutul fisierului am folosit 'use client' pentru a semnala next.js că e o componentă care rulează pe client (front).
Componenta mea conține două stări:
timeLeft (numărătoare inversă de 60 secunde)
canResend (dacă butonul "Trimite din nou" este activ). Cu ajutorul useEffect, timerul scade automat o dată pe secundă, iar când ajunge la 0, activăm butonul. La click pe "Trimite din nou", simulăm retrimiterea emailului și repornim timerul.
Layout-ul conține un titlu, o descriere cu instrucțiuni, un buton pentru retrimiterea emailului (care cumva ar trebui sa fie dezactivat până expiră …
> #028 confirm mail

- src/lib/logic/AuthValidators.js
Schimbat email validation regex si functia testValidEmailFormat
> #006 more validation

- src/app/auth/extra-data-required/page.js
- src/lib/logic/AuthValidators.js
S-a rezolvat validare login (required email)
S-a rezolvat redirect
> #006 qa changes

- src/app/auth/form-inchiriere-1/formInchiriere.module.css
- src/app/auth/form-inchiriere-1/page.js
- src/app/page.js
Am adaugat un formular simplu pentru inchirierea produselor, unde utilizatorii pot introduce:
1. CNP (13 cifre exact)
2. Adresa de domiciliu
3. Numarul de zile pentru inchiriere
Functionalitati cheie:
• Validare in timp real pentru fiecare camp
• Buton "Goleste" care reseteaza formularul
• Butonul "Inchiriaza" se activeaza (se face gradientul portocaliu) doar cand toate campurile sunt completate corect.
> Form inchiriere Tip 1

- src/app/auth/extra-data-required/page.js
- src/app/auth/login/page.js
- src/app/auth/register/page.js
- src/app/home/components/Sidebar.js
- src/lib/components/form/Form.js
- src/lib/components/form/FormStyles.module.css
**#046_Creare_buton**
- in pagina de login am inlocuit link-ul pentru "Ai uitat parola?" cu un buton
- width: la fel ca  butonului de Inregistrare
- border negru
- background alb
**#046_Eliminare_LOGOUT**
-  in landing page am eliminat butonul de logout din stanga, jos
**#045_Rezolvare_redirectionari**
- redirectionare de la inregistrare1 la validare mail (butonul Creaza cont)
**#043_Schimbare_Label-uri_Form**
- in formularele de register1 si register2 am schimbat label-urile pentru field-uri (in task pe trello scria si de formularul login, dar acolo nu am nici un label cu numele respective) :  nr.matricol -> nr de marca , universitate -> centru
> #043 sprint1 postfixes

- src/app/home/echipamente/echipament/Echipament.module.css
- src/app/home/echipamente/echipament/page.js
S-au facut modificari, astfel incat sa se poate faca build.
> #035 build fixes

- src/app/auth/forgot-password/forgotPassword.module.css
- src/app/auth/forgot-password/page.js
- src/app/auth/login/page.js
Pagina de resetare parola contine: 
- Titlul: Ai uitat parola?
- Paragraf scurt - instructiuni proces
- Un field cu label E-mail/ E-mail institutional
- Un buton de trimitere 
- Buton de back (stanga sus)
Redirectionari:
- Ti-ai uitat parola (din login page) → Forgot password page
- Buton back (forgot password page)-> Login page
- Buton "Trimite" (forgot password page)-> Pagina de "Mail-ul a fost trimis" (deja existenta): /auth/confirm-mail
> #053-pagina-resetare-parola

- src/app/home/inchiriere/formInchiriere.module.css
Am facut designul responsive si am eliminat utilizarea rem, am adaugat px in schimb.
Imi da chestia aia cu hidratarea, insa nu i-am dat de cap si nici nu cred ca strica cu ceva.
> #058-responsive-inchiriere

- src/app/home/inchiriere/form-inchiriere-2/page.js
A fost nevoie de un validator care sa imi permita sa incarc la documentatia necesara inchirierii unui produs sa pun doar PDF. Atunci cand dau click pe selecteaza, mi se dechid doar documentele pdf din PC, iar daca incarc prin drag and drop un fisier de alt tip (ex. docx), atunci apare mesaj de eroare sub caseta si trebuie golita cererea.
> #057 validare pdf

- src/app/auth/extra-data-required/page.js
A fost nevoie doar sa repar scrisul de pe butonul negru "Finalizeaza" si sa adaug diacritite pe pagina extra data required.
Puteti da approve fara sa va tare uitati, era usor tare=)
> #056 finalizeaza buton si adaugare diacritice

- src/app/home/testing/listare-cerere/page.js
- src/lib/components/home/CerereListing.js
- src/lib/components/home/CerereListing.module.css
- src/lib/routes.js
**_#066_Componenta_listare_cerere_**
Componenta pentru pagina de cereri a studentului/cercetatorului
Contine: 
- titlu
- label: poate fi mentenanta (rosu) / valabil (verde)
- am pus culoarea textului din label alb (in loc de negru) ca sa se vada mai bine
- width-ul 100% pe container
- componenta este dinamica
- functionalitate onClick
> #066 componenta listare cerere

- src/app/home/confirmare-decizie-admin/confirmDecisionAdmin.module.css
- src/app/home/confirmare-decizie-admin/page.js
- src/lib/routes.js
_**#086-Pagina confirmare decizie admin**_
- pagina contine un div cu mesajul de confirmare (s-a stabilit ca va fi 50% din container si centrat pana se modifica design-ul)
- dupa 7 secunde se intoarce la pagina anterioara
(! cand se implementeaza pagina de administrare utilizator trebuie facuta redirectionarea corect)
#072
-adaugat buton de back
-page responsive(s-a modificat width-ul div-ului cu mesajul de confirmare la 70% pt. desktop, 90% pt. tableta si 95% pt. telefon)
> #086-Pagina confirmare decizie admin

- Dockerfile
- package-lock.json
- package.json
- src/app/home/testing/listare-cerere/page.js
- src/lib/components/home/echipamente/CerereLIistingLaborant.module.css
- src/lib/components/home/echipamente/CerereListingLaborant.js
**#068 Componenta listare cerere (laborant)**
Contine:
- titlu
- label: poate fi "Rejected" (rosu) / "Accepted" (verde) / "Pending" (albastru)
- width-ul 100% pe container
- componenta este dinamica
- functionalitate onClick
> #068 componenta listare cerere laborant

- src/app/home/form-adaugare-produs/formAdaugareProdus.module.css
- src/app/home/form-adaugare-produs/page.js
Doamne, greu o fost.
Deci, a trebuit sa fac un formular in care un admin sa poata sa adauge un produs. Punea un titlu, descriere, etc. Are permisiunea de a incarca maxim 10 imagini, lucru de care este avertizat atunci cand le incarca. Am utilizat o metoda de stocare locala a acelor imagini incluse, astfel incat adminul sa poata sa verifice ce imagini a incarcat. De asemenea, are posibilitatea de a sterge acele imagini prin butonul rosu din dreapta sus.
Formularul devine valid atunci cand toate campurile au fost completate. Atunci, butonul de Adauga produs va capata culoarea gradient preluata din logo-ul ISMA. 
Thanks for reading.
> #082 form adaugare produs

- src/app/home/testing/listare-cerere/page.js
- src/lib/components/home/echipamente/ListareUser.js
- src/lib/components/home/echipamente/ListareUser.module.css
**_#092 - Componenta listare users_**
Componenta pt pagina de administrare useri (admin).
Contine: 
- Denumirea utilizatorului
- Label  -> Pending / Rejected / Approved / avrevierea facultatii (FEEA, FII, etc)
> #092 - Componenta listare users

- src/lib/components/home/echipamente/ProdusListing.js
- src/lib/components/home/echipamente/ProdusListing.module.css
Componenta listare produs contine:
- denumire
- label(valabil/mentenanta)
> '#091_Componenta LISTARE PRODUS'

- package-lock.json
- package.json
- src/app/home/produs-adaugat-succes/page.js
- src/app/home/produs-adaugat-succes/produsAdaugatSucces.module.css
- src/lib/routes.js
A fost nevoie sa fac acel box gălbui-portocaliu sa aiba urmatoarele dimensiuni:
1. 70% ecran pc
2. 90% ecran tableta
3. 95% ecran telefon.
> #083 Produsul a fost adaugat cu succes

- src/app/home/testing/listare-cerere/page.js
- src/lib/components/home/echipamente/ProdusListing.js
- src/lib/components/home/echipamente/ProdusListing.module.css
- src/lib/fonts/Montserrat.js
**_#094 - Fixed Componenta Listare Produs_**
- am aplicat design-ul pentru componenta de listare de produs (pagina admin)
> #094 - fix componenta listare produs

- src/app/home/cereri-useri/cereriUseri.module.css
- src/app/home/cereri-useri/page.js
Am pus calea cereri-useri pentru ca voi aduce ulterior, dupa ce voi avea dat merge la toate taskurile, toate paginile de cereri in acelasi folder numit cereri. Momentan il las asa.
Tot ulterior, cand voi avea path-ul corect, voi adauga si in routes.js calea catre toate aceste pagini de cerere.
> #087-cerere-useri

- src/app/home/cereri-laborant/adminCereriLaborant.module.css
- src/app/home/cereri-laborant/page.js
Aceasta pagina se adreseaza utilizatorilor de tip LABORANT!
A fost nevoie sa fac import la componentele SearchAndFilter si CerereListingLaborant.
Ce e cu chestia aia cu x3Q7u?
Raspuns:
.styles_componentTitle__x3Q7u:
Este o clasă generată automat de CSS Modules
Numele original era doar .componentTitle
Sufixul aleatoriu (__x3Q7u) este adăugat pentru a evita conflicte de nume
Am incercat sa fac titlul Cereri mai frumos=)
> #089 administrare cereri laborant

- src/lib/routes.js
> Update routes.js hotfix

- src/app/home/cereri-admin/listareCereriAdmin.module.css
- src/app/home/cereri-admin/page.js
Cam acelasi mod de rezolvare ca la taskul de la administrarea cererilor la un laborant
> #105 pagina listare cereri admin

- src/app/home/testing/administrare/administrare-utilizatori/administrareUtilizatori.module.css
- src/app/home/testing/administrare/administrare-utilizatori/page.js
- src/lib/components/popups/UserDetailsPopup.js
- src/lib/components/popups/UserDetailsPopup.module.css
Am implementat poup-ul de vizualizare a datelor utilizatorului de catre admin
Pagina de testare: home/testing/administrare/administrare-utilizatori
Am lasat butonul de X in partea stanga a popup-ului deoarece am eliminat toate elementele position:absolute
> #101-Vizualizare_detalii_user-ca-admin

- src/app/home/administrare/administrare-echipamente/listareProduseAdmin.module.css
- src/app/home/administrare/administrare-echipamente/page.js
- src/app/home/administrare/page.js
- src/app/home/cereri-useri/page.js
- src/app/home/cereri/administrareUseri.module.css
- src/app/home/cereri/page.js
- src/app/home/echipamente/echipament/Echipament.module.css
- src/app/home/echipamente/echipament/page.js
- src/app/home/form-adaugare-produs/page.js
- src/app/home/inchiriere/echipament-complex/page.js
- src/app/home/inchiriere/echipament-simplu/page.js
- src/app/home/inchiriere/formInchiriere.module.css
- src/lib/components/home/Sidebar.js
- src/lib/components/home/echipamente/ListareUser.js
- src/lib/components/home/echipamente/ListareUser.module.css
- src/lib/components/home/echipamente/ProductCard.js
- src/lib/components/home/echipamente/ProdusListing.js
- src/lib/components/home/echipamente/ProdusListing.module.css
- src/lib/components/home/echipamente/RequestDetailsPopup.js
**_#111 - redirectionari pagini_**
(+fix componente unde a fost nevoie ca sa se poata face redirectionarile)
(!) = pagina este inca in code review/progress; am pus doar ruta trecuta in task-uri pe trello
**Pagina Administrare (a admin-ului):**
- cele  2 butoare (una catre pagina de administrare useri, cealalta catre administrare echipamente)
**Pagina Administrare-Echipamente:**
- am adaugat buton de back
- click pe componenta -> pagina administrare produse (! - #100)
* a trebuit modificata componenta ProdusListing sa accepte click pe componenta/edit separat
* pentru iconita de edit este nevoie de #102
* butonul de adaugare produs merge deja
**Pagina Administrare-Cereri (/home/cereri):**
- am adaugat buton de back
* pentru iconita de edit este nevoie de #103
* pentru click pe componenta …
> #111 - redirectionari pagini
